/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check endpoint
     * @description Returns the current health status of the API service
     */
    get: operations['getHealthStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponseDto: {
      /**
       * @description Overall health status
       * @example healthy
       * @enum {string}
       */
      status: 'healthy' | 'degraded' | 'unhealthy';
      /**
       * Format: date-time
       * @description Health check timestamp
       * @example 2023-12-04T10:30:00Z
       */
      timestamp: string;
      /**
       * @description Application version
       * @example 1.0.0
       */
      version?: string;
      /**
       * @description Server uptime in seconds
       * @example 86400
       */
      uptime?: number;
      /** @description Detailed health information (when detailed=true) */
      details?: {
        database?: {
          /** @example connected */
          status?: string;
          /**
           * @description Response time in milliseconds
           * @example 15
           */
          responseTime?: number;
        };
        memory?: {
          /**
           * @description Memory usage percentage
           * @example 45.2
           */
          usage?: number;
          /**
           * @description Total available memory
           * @example 8GB
           */
          total?: string;
        };
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealthStatus: {
    parameters: {
      query?: {
        /** @description Include detailed health information */
        detailed?: boolean;
        /** @description Check specific service components */
        components?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      /** @description Service is unhealthy */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
}
